name: try_wupper
description: An absolute bare-bones web app using wupper.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
  flutter_lints: ^3.0.1

dependencies:
  wupper:
    path: ../
