image: dart

stages:
  - test

code_analyze:
  tags:
    - docker
  stage: test
  dependencies: []
  script:
    - dart pub get
    - cd example; dart pub get; cd ..
    - dart format lib/ test/ example/lib example/test example/web --set-exit-if-changed
    - dart analyze
