name: wupper
description: Dart Web UI Framework based on HTML Elements inspired by Flutter
version: 1.0.0
homepage: https://gitlab.com/famedly/company/frontend/libraries/wupper

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
