name: 🛠️ Feature
description: "Create an new issue for a new Feature in Famedly"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
      - label:
          I could not find a solution in the existing issues, docs, nor discussions
        required: true
  - type: textarea
    id: problem
    attributes:
      label: Describe your problem
      description: Please describe your problem this new feature is supposed to solve.
      placeholder: Describe the problem you have
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: Which solution do you propose?
      placeholder: As a [type of user], I want [some goal] so that [some reason].
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the Famedly are you using.
  - type: textarea
    id: security
    attributes:
      label: Security requirements
      description: Plese add more information in terms of security requirements.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Please add any other infos that could be useful.
